global_frame_id: map

holonomic_robot: false

max_vel_x: 3.0
min_vel_x : 0.1
max_vel_theta: 4.0
min_vel_theta: -4.0
min_in_place_vel_theta: 0.4

escape_vel: -0.1

y_vels: [0.0, 0.0, 0.0, 0.0] 


acc_lim_theta: 3.2
acc_lim_x: 2.5
acc_lim_y: 0.0

oscillation_reset_dist: 0.1


xy_goal_tolerance: 0.1


meter_scoring: true
pdist_scale: 4.0
gdist_scale: 3.0
occdist_scale: 0.1



