local_costmap:
  robot_base_frame: base_link
  global_frame: odom
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true

  width: 10.0
  height: 10.0
  resolution: 0.05

  plugins: 
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}
  obstacles:
    observation_sources: base_scan
    base_scan: {data_type: LaserScan, sensor_frame: base_laser_link, clearing: true, marking: true, topic: /scan_raw}
  
  inflation:
    inflation_radius: 0.7
